# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65e56a963c7a2ac0a75efbd5f63a2898fc76a73cb3efd6c8e746bc93d393aed2953515d23bdf8b7a44378ff9bd998e22516924c4951d52239cafcd4fed763b1c

test:
  secret_key_base: 7778fb0b8caf900c947fbb7d6eefe379eba78fa0a339643c54596c27318c0f172d0a1b7b90850422f4055b19692b72a0c5b08813057de05ae4342cbea57d8a12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
